### ISSUE TITLE
Shape

### ISSUE THREAD

**Issue by vanko69** [Plumillon/ChipView#2]
I am looking at your ChipView, and I like it a lot. Just one question: Can you change the shape of the chips? For example make them square or rectangle? It is not a issue, but i don't know where to put my question. Awesome work!

**Comment by Plumillon** [comment]
Hi vanko69 and thanks for you kind words !
Yes you can by changing the background res

You have two choices : 
1. Set it via the ```ChipViewAdapter.setChipBackgroundRes``` (all Chip will be the same)
2. If you want to control it at Chip level : 
  * You need to implement you own [ChipViewAdapter](https://github.com/Plumillon/ChipView/blob/master/library/src/main/java/com/plumillonforge/android/chipview/ChipViewAdapter.java)  (see [the one](https://github.com/Plumillon/ChipView/blob/master/app/src/main/java/com/plumillonforge/android/chipview/sample/MainChipViewAdapter.java) from the sample app)
  * Then @Override ```getBackgroundRes(int position)``` and return the corresponding res

Keep in mind you need to provide a [Drawable res](http://developer.android.com/guide/topics/resources/drawable-resource.html) so if you want to support different colors for state, you need to provide a selector like so (for a rectangle shape, with padding) : 
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true">
        <shape>
            <solid android:color="@color/chip_background_selected" />
            <padding android:bottom="2dp" android:left="6dp" android:right="6dp" android:top="2dp" />
        </shape>
    </item>
    <item android:state_focused="true">
        <shape>
            <solid android:color="@color/chip_background_selected" />
            <padding android:bottom="2dp" android:left="6dp" android:right="6dp" android:top="2dp" />
        </shape>
    </item>
    <item>
        <shape>
            <solid android:color="@color/chip_background" />
            <padding android:bottom="2dp" android:left="6dp" android:right="6dp" android:top="2dp" />
        </shape>
    </item>
</selector>
```

I hope that will answer you question !

**Comment by vanko69** [comment]
10x. You helped me a lot. :)

**Comment by Plumillon** [comment]
Good, I hope you achieved what you needed !
