### ISSUE TITLE
Possibility to change text color

### ISSUE THREAD

**Issue by khrizt** [Plumillon/ChipView#5]
Hi,

I'd love to have the ability to change the text color without creating a layout for the ChipViews, would be that possible?

Thanks

**Comment by Plumillon** [comment]
Hi khrizt,
You can do it via a custom adapter, you have an example of changing the text color here : https://github.com/Plumillon/ChipView/blob/master/app/src/main/java/com/plumillonforge/android/chipview/sample/MainChipViewAdapter.java#L74

In fact, the TextView created have the `android.R.id.text1` id by default, so you can access it this way

**Comment by khrizt** [comment]
Thanks man, sorry I didn't see that one.

**Comment by Plumillon** [comment]
Np, I'm here to help :)
Also, the `onLayout` adapter method is a bit of "all-in" where you got access to all the Chip View
Let me know if you got any question
