### ISSUE TITLE
How to Use It?

### ISSUE THREAD

**Issue by lokeshdesai403** [Plumillon/ChipView#7]
How To use It?

i m adding this zip file provided by u in eclipse as external library. than trying to to add chipview by programically by i got this error:

The following classes could not be found:
- com.plumillonforge.android.chipview.ChipView 

i m new in android programming

**Comment by Plumillon** [comment]
Hi,
Do you include it as a project library ?
Please read instructions here for example : http://stackoverflow.com/a/9283084/328845

**Comment by lokeshdesai403** [comment]
Thank u sir for ur reply

I  used it as an external library in my Android project .but I m not able
to implement chip interface in my project or any other interface...contain
in that zip file
